# Generated by Django 3.2 on 2021-07-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='cars/images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.car')),
            ],
            options={
                'verbose_name': 'CarImage',
                'verbose_name_plural': 'CarImages',
            },
        ),
    ]
